ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Models/Vehiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCInicial.Models
{
    public class Vehiculo
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Color { get; set; }

        public Serie Serie { get; set; }
        public int IdSerie { get; set; }

        public List<int> ExtrasSeleccionados { get; set; }
        public List<VehiculosExtras> ExtrasDelVehiculo { get; set; }
    }
}

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using MVCInicial.Models;
using System.Data.SqlClient;

namespace MVCInicial.Controllers
{
    public class VehiculoTotal
    {
        public string Nom_marca { get; set; }
        public string Nom_serie { get; set; }
        public string Matricula { get; set; }
        public string Color { get; set; }
    }

    public class VehiculoController : Controller
    {
        Contexto BD = new Contexto();

        // GET: Vehiculo
        public ActionResult Index()
        {
            ViewBag.cualquiera = BD.Marcas.ToList();
            // IList<Vehiculo> Vehiculos = BD.Vehiculos.ToList();ç
            // No meterlo en un ViewBag, que da NullPointerException
            // Ojo a la forma que usa el para hacer un generico
            var Vehiculos = BD.Vehiculos.Include(x => x.Serie);
            // recordar: x == BD.Vehiculos
            return View(Vehiculos.ToList());
        }

        // GET: Vehiculo/Details/5
        public ActionResult Details(int id)
        {
            // Vehiculo Rescatado = BD.Vehiculos.Find(id); // El find no rula con los includes
            Vehiculo Rescatado = BD.Vehiculos.Include(v => v.Serie).FirstOrDefault(v => v.Id == id);
            ViewBag.cualquiera = BD.Marcas.ToList();
            return View(Rescatado);
        }

        // GET: Vehiculo/Create
        public ActionResult Create()
        {
            ViewBag.IdSerie = new SelectList(BD.Series, "Id", "Nombre");
            ViewBag.ExtraList = new MultiSelectList(BD.Extras, "Id", "TipoExtra");
            return View();
        }

        // POST: Vehiculo/Create
        [HttpPost]
        public ActionResult Create(Vehiculo Vehiculo)
        {
            try
            {
                BD.Vehiculos.Add(Vehiculo);
                BD.SaveChanges();
                // Hay que hacer tantos ADDs como EXTRAS HAYAMOS METIDO
                foreach(var extraID in Vehiculo.ExtrasSeleccionados)
                {
                    /*
                     * // git gudff
                    VehiculosExtras Relacion = new VehiculosExtras();
                    Relacion.IdExtra = extraID;
                    Relacion.IdVehiculo = Vehiculo.Id;
                    */
                    // Forma guay
                    VehiculosExtras Relacion = new VehiculosExtras() { IdVehiculo = Vehiculo.Id, IdExtra = extraID };
                    BD.VehiculosExtras.Add(Relacion);
                    BD.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vehiculo/Edit/5
        public ActionResult Edit(int id)
        {
            /*
            var VehiculoEditado = (
                from vehiculos in BD.Vehiculos.Include(vehiculos => vehiculos.Serie)
                where vehiculos.Id == id
                select vehiculos).FirstOrDefault();
            // Vehiculo VehiculoEditado = Vehiculos[0]; // ACORDARSE DEL PUTO MÉTODO
            */

            // Agustín ha enseñado esta manera
            
            Vehiculo VehiculoEditado = BD.Vehiculos.Find(id);
            ViewBag.IdSerie = new SelectList(BD.Series, "Id", "Nombre", VehiculoEditado.IdSerie);
            return View(VehiculoEditado);
        }


        [HttpPost]
        public ActionResult Edit(int id, Vehiculo VehiculoSeleccionado)
        {
            try
            {
                Vehiculo Vehiculo = BD.Vehiculos.SingleOrDefault(v => v.Id == id);
                Vehiculo.Matricula = VehiculoSeleccionado.Matricula;
                Vehiculo.IdSerie = VehiculoSeleccionado.IdSerie;
                Vehiculo.Color = VehiculoSeleccionado.Color;
                BD.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Vehiculo/Delete/5
        public ActionResult Delete(int id)
        {
            Vehiculo v = BD.Vehiculos.Find(id);
            return View(v);
        }

        // POST: Vehiculo/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Vehiculo Borrar = BD.Vehiculos.Find(id);
                BD.Vehiculos.Remove(Borrar);
                BD.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // Va a devolver un listado de vehículos
        // Mirar la sintxis de esto: es como Python: si no se le pasa un parametro, toma el por defecto
        public ActionResult Busqueda(String busca="")
        {
            var Vehiculos = (
                from vehiculos in BD.Vehiculos.Include(vehiculos => vehiculos.Serie)
                where vehiculos.Matricula.Contains(busca)
                select vehiculos
                ).ToList();
            return View(Vehiculos);
        }

        public ActionResult BusquedaDropDown(String Desplegable="0")
        {
            SelectList ListaVehiculos = new SelectList(BD.Vehiculos, "Id", "Matricula");
            ViewBag.Desplegable = ListaVehiculos;
            int SelectId = int.Parse(Desplegable);
            var Vehiculos = (
                from vehiculos in BD.Vehiculos.Include(vehiculos => vehiculos.Serie)
                where vehiculos.Id == SelectId 
                select vehiculos
                ).ToList();
            return View(Vehiculos);
        }

        /*
        public ActionResult FiltradoCompleto(int DespegableMarcas = 0, int DespegableSeries = 0)
        {
            // Lo que le paso realmente es la id, pero la llamo así porque me es más cómodo porque o ha cogido por defecto
            SelectList ListaTodasMarcas = new SelectList(BD.Marcas, "Id", "Nombre");
            var Datos = (
                from Series in BD.Series
                where Series.IdMarca == DespegableMarcas
                select Series
                ).ToList();
            SelectList ListaSeriesFiltradas = new SelectList(Datos, "Id", "Nombre");
            ViewBag.DesplegableSeries = ListaSeriesFiltradas;
            ViewBag.DespegableMarcas = ListaTodasMarcas;
            var Coches = (
                from Vehiculo in BD.Vehiculos
                where Vehiculo.IdSerie == DespegableSeries
                select Vehiculo
                ).ToList();
            SelectList CochesLIST = new SelectList(Coches, "Id", "Matricula" + "  Color");
            ViewBag.SusVehiculos = CochesLIST;
            return View();
        }
        */

        // El de agustin
        public ActionResult Listado(int MarcaId = 1, int SerieId = 0)
        {
            ViewBag.MarcaID = new SelectList(BD.Marcas, "Id", "Nombre");
            ViewBag.SerieID = new SelectList(BD.Series.Where(e => e.IdMarca == MarcaId), "Id", "Nombre");
            var Vehiculos = BD.Vehiculos.Include(x => x.Serie).Where(e => e.IdSerie == SerieId);
            return View(Vehiculos.ToList());
        }

        public ActionResult listarPorColor(String color="")
        {
            // Ojito a la modificación que hay que cascarle: el string con la indicacion de que va  coger un parametro
            // y una dupla nombre / valor
            var Lista = BD.Database.SqlQuery<VehiculoTotal>("getVehiculosPorColor @ColorSel", new SqlParameter("@ColorSel", color)).ToList();
            var Colores = BD.Vehiculos.Select(l => l.Color).Distinct().ToList();
            // ViewBag.color = Colores; // Se debe llamar con el nombre del parámetro
            // A diferencia de lo que se dijo el otro dia, vamos a crear un selectlist con el viewbag para cargarlo directamente en la vista
            ViewBag.color = new SelectList(Colores);
            return View(Lista);
        }
    }
}

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/Busqueda.cshtml
@model IEnumerable<MVCInicial.Models.Vehiculo>

@{
    ViewBag.Title = "Busqueda";
}

<h2>Busqueda</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdSerie)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}
    <h1>ENCUENTRA UN COCHE</h1>
    <hr />
    <form method="get" name="cochechico">
        <label for="matricula">Matrícula: </label>
        <input type="text" value="" name="busca" placeholder="Introduce la matrícula" />
        <br />
        <input type="submit" value="BUSCA" />
    </form>

    <form method="get" name="cochechico">
        <input type="search" value="" name="busca" hidden placeholder="Introduce la matrícula" />
        <input type="submit" value="VOLVER" />
    </form>

</table>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/BusquedaDropDown.cshtml
@model IEnumerable<MVCInicial.Models.Vehiculo>

@{
    ViewBag.Title = "BusquedaDropDown";
}

<h2>BusquedaDropDown</h2>

<form method="get" name="Id">
@Html.DropDownList("Desplegable", "--Macarrones--")
<input type="submit" value="taclaclás" />
</form>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdSerie)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/Create.cshtml
@model MVCInicial.Models.Vehiculo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdSerie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdSerie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdSerie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExtrasSeleccionados, "Selección de Extras", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.ExtrasSeleccionados, new MultiSelectList(ViewBag.ExtraList, "value", "text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdSerie, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/Delete.cshtml
@model MVCInicial.Models.Vehiculo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Quieres patatas fritas?</h3>
<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdSerie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSerie)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Vehiculo", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/Details.cshtml
@model MVCInicial.Models.Vehiculo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serie.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Serie.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Serie.Marca)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/Edit.cshtml
@model MVCInicial.Models.Vehiculo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Vehiculo", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>
        <!--  ESTO ES LO QUE GENERA -->
        <!--
        <div class="form-group">
            @Html.LabelFor(model => model.IdSerie, new { htmlAttributes = new { @class = "control-label col-md-2" } })
            <div class="col-md-10">
                @Html.ValidationMessageFor(model => model.IdSerie, "", new { @class = "text-danger" })
            </div>
        </div>
            -->
        <div class="form-group">
            @Html.LabelFor(model => model.IdSerie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdSerie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdSerie, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/FiltradoCompleto.cshtml
@model MVCInicial.Models.Vehiculo

@{
    ViewBag.Title = "FiltradoCompleto";
}

<h2>FiltradoCompleto</h2>

<div>
    <h4>Vehiculo</h4>
    <hr />
    <form method="get" name="Id" onchange="submit()">
        <h1>
            MARCAS
            @Html.DropDownList("DespegableMarcas", "--Macarrones--")
        </h1>
        <hr />
        <h1>
            MODELOS
            @Html.DropDownList("DesplegableSeries", "--Macarrones--")
        </h1>
        <input type="submit" value="FiltradoCompleto" />
    </form>


    <hr />

    <table>

@foreach (var item in ViewBag.SusVehiculos)
{
    <tr>
        <td>
           @item.Matricula
        </td>
        <td>
            @item.Color
        </td>
    </tr>
}
    </table>

</div>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/Index.cshtml
@model IEnumerable<MVCInicial.Models.Vehiculo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Serie.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdSerie)
        </th>
        <th>
            Operaciones
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Serie.IdMarca)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/Listado.cshtml
@model IEnumerable<MVCInicial.Models.Vehiculo>

@{
    ViewBag.Title = "Listado";
}

<h1>Selecciona los filtros</h1>

    @Html.DropDownList("MarcaId", null, htmlAttributes: new { @class = "form-control", onchange="submit()"})
    @Html.DropDownList("SerieId", null, htmlAttributes: new { @class = "form-control", onchange = "submit()" })


<hr />

<h2>Listado</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdSerie)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Matricula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdSerie)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

ACCESO-A-DATOS/SEGUNDA/Code/MVCInicial/MVCInicial/Views/Vehiculo/listarPorColor.cshtml
@model IEnumerable<MVCInicial.Models.Vehiculo>

@{
    ViewBag.Title = "listarPorColor";
}

<h2>listarPorColor</h2>
     @*
    ESTO ES LO QUE TENÍA YO ANTES
    <select name="Lista2" id="Lista2">
    @foreach (string color in ViewBag.ColorData)
    {
        <option value="@color">@color</option>
    }
    </select>
         *@
<form method="get">

    @Html.DropDownList("color");
    <input type="submit" value="Buscar" />
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Matricula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdSerie)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Matricula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdSerie)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
