MULTIDISPOSITIVOS/JSF/RESOURCES/Prestados y práctica/MIGUEL/Bliblioteca2/src/java/Controladores/AutorPremioController.java
package Controladores;

import Entidades.AutorPremio;
import Controladores.util.JsfUtil;
import Controladores.util.PaginationHelper;
import Entidades.Autores;
import Entidades.Premios;
import Facades.AutorPremioFacade;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("autorPremioController")
@SessionScoped
public class AutorPremioController implements Serializable {

    private AutorPremio current;
    private DataModel items = null;
    @EJB
    private Facades.AutorPremioFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    
    private Autores autor;
    private List<AutorPremio> lista=new ArrayList();

    public List<AutorPremio> getLista() {
        return lista;
    }
    public void setLista(List<AutorPremio> lista) {
        this.lista = lista;
    }
     public Autores getAutor() {
        return autor;
    }
    public void setAutor(Autores autor) {
        this.autor = autor;
    }
    
    
    public AutorPremioController() {
    }

    public AutorPremio getSelected() {
        if (current == null) {
            current = new AutorPremio();
            current.setAutorPremioPK(new Entidades.AutorPremioPK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private AutorPremioFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (AutorPremio) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new AutorPremio();
        current.setAutorPremioPK(new Entidades.AutorPremioPK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            current.getAutorPremioPK().setCodPremio(current.getPremios().getCodPremio());
            current.getAutorPremioPK().setCodAutor(current.getAutores().getCodAutor());
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AutorPremioCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (AutorPremio) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            current.getAutorPremioPK().setCodPremio(current.getPremios().getCodPremio());
            current.getAutorPremioPK().setCodAutor(current.getAutores().getCodAutor());
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AutorPremioUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (AutorPremio) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("AutorPremioDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public AutorPremio getAutorPremio(Entidades.AutorPremioPK id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = AutorPremio.class)
    public static class AutorPremioControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AutorPremioController controller = (AutorPremioController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "autorPremioController");
            return controller.getAutorPremio(getKey(value));
        }

        Entidades.AutorPremioPK getKey(String value) {
            Entidades.AutorPremioPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new Entidades.AutorPremioPK();
            key.setCodAutor(Integer.parseInt(values[0]));
            key.setCodPremio(Integer.parseInt(values[1]));
            key.setAnio(Integer.parseInt(values[2]));
            return key;
        }

        String getStringKey(Entidades.AutorPremioPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getCodAutor());
            sb.append(SEPARATOR);
            sb.append(value.getCodPremio());
            sb.append(SEPARATOR);
            sb.append(value.getAnio());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof AutorPremio) {
                AutorPremio o = (AutorPremio) object;
                return getStringKey(o.getAutorPremioPK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + AutorPremio.class.getName());
            }
        }

    }
    public void obtenerPremiosAutor(){
        lista = ejbFacade.premiosAutor(autor);
    }

}

MULTIDISPOSITIVOS/JSF/RESOURCES/Prestados y práctica/MIGUEL/Bliblioteca2/web/autorPremio/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAutorPremioTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateAutorPremioLabel_autorPremioPK_anio}" for="autorPremioPK_anio" />
                    <h:inputText id="autorPremioPK_anio" value="#{autorPremioController.selected.autorPremioPK.anio}" title="#{bundle.CreateAutorPremioTitle_autorPremioPK_anio}" required="true" requiredMessage="#{bundle.CreateAutorPremioRequiredMessage_autorPremioPK_anio}"/>
                    <h:outputLabel value="#{bundle.CreateAutorPremioLabel_autores}" for="autores" />
                    <h:selectOneMenu id="autores" value="#{autorPremioController.selected.autores}" title="#{bundle.CreateAutorPremioTitle_autores}" required="true" requiredMessage="#{bundle.CreateAutorPremioRequiredMessage_autores}">
                        <f:selectItems value="#{autoresController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateAutorPremioLabel_premios}" for="premios" />
                    <h:selectOneMenu id="premios" value="#{autorPremioController.selected.premios}" title="#{bundle.CreateAutorPremioTitle_premios}" required="true" requiredMessage="#{bundle.CreateAutorPremioRequiredMessage_premios}">
                        <f:selectItems value="#{premiosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{autorPremioController.create}" value="#{bundle.CreateAutorPremioSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{autorPremioController.prepareList}" value="#{bundle.CreateAutorPremioShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateAutorPremioIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

MULTIDISPOSITIVOS/JSF/RESOURCES/Prestados y práctica/MIGUEL/Bliblioteca2/web/autorPremio/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditAutorPremioTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAutorPremioLabel_autorPremioPK_anio}" for="autorPremioPK_anio" />
                    <h:inputText id="autorPremioPK_anio" value="#{autorPremioController.selected.autorPremioPK.anio}" title="#{bundle.EditAutorPremioTitle_autorPremioPK_anio}" required="true" requiredMessage="#{bundle.EditAutorPremioRequiredMessage_autorPremioPK_anio}"/>
                    <h:outputLabel value="#{bundle.EditAutorPremioLabel_autores}" for="autores" />
                    <h:selectOneMenu id="autores" value="#{autorPremioController.selected.autores}" title="#{bundle.EditAutorPremioTitle_autores}" required="true" requiredMessage="#{bundle.EditAutorPremioRequiredMessage_autores}">
                        <f:selectItems value="#{autoresController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditAutorPremioLabel_premios}" for="premios" />
                    <h:selectOneMenu id="premios" value="#{autorPremioController.selected.premios}" title="#{bundle.EditAutorPremioTitle_premios}" required="true" requiredMessage="#{bundle.EditAutorPremioRequiredMessage_premios}">
                        <f:selectItems value="#{premiosController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{autorPremioController.update}" value="#{bundle.EditAutorPremioSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditAutorPremioViewLink}"/>
                <br />
                <h:commandLink action="#{autorPremioController.prepareList}" value="#{bundle.EditAutorPremioShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditAutorPremioIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

MULTIDISPOSITIVOS/JSF/RESOURCES/Prestados y práctica/MIGUEL/Bliblioteca2/web/autorPremio/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListAutorPremioTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListAutorPremioEmpty}" rendered="#{autorPremioController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{autorPremioController.items.rowCount > 0}">
                    <h:outputText value="#{autorPremioController.pagination.pageFirstItem + 1}..#{autorPremioController.pagination.pageLastItem + 1}/#{autorPremioController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{autorPremioController.previous}" value="#{bundle.Previous} #{autorPremioController.pagination.pageSize}" rendered="#{autorPremioController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{autorPremioController.next}" value="#{bundle.Next} #{autorPremioController.pagination.pageSize}" rendered="#{autorPremioController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{autorPremioController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAutorPremioTitle_autorPremioPK_anio}"/>
                            </f:facet>
                            <h:outputText value="#{item.autorPremioPK.anio}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAutorPremioTitle_autores}"/>
                            </f:facet>
                            <h:outputText value="#{item.autores}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAutorPremioTitle_premios}"/>
                            </f:facet>
                            <h:outputText value="#{item.premios}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{autorPremioController.prepareView}" value="#{bundle.ListAutorPremioViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{autorPremioController.prepareEdit}" value="#{bundle.ListAutorPremioEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{autorPremioController.destroy}" value="#{bundle.ListAutorPremioDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{autorPremioController.prepareCreate}" value="#{bundle.ListAutorPremioCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListAutorPremioIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

MULTIDISPOSITIVOS/JSF/RESOURCES/Prestados y práctica/MIGUEL/Bliblioteca2/web/autorPremio/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewAutorPremioTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAutorPremioLabel_autorPremioPK_anio}"/>
                    <h:outputText value="#{autorPremioController.selected.autorPremioPK.anio}" title="#{bundle.ViewAutorPremioTitle_autorPremioPK_anio}"/>
                    <h:outputText value="#{bundle.ViewAutorPremioLabel_autores}"/>
                    <h:outputText value="#{autorPremioController.selected.autores}" title="#{bundle.ViewAutorPremioTitle_autores}"/>
                    <h:outputText value="#{bundle.ViewAutorPremioLabel_premios}"/>
                    <h:outputText value="#{autorPremioController.selected.premios}" title="#{bundle.ViewAutorPremioTitle_premios}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{autorPremioController.destroyAndView}" value="#{bundle.ViewAutorPremioDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewAutorPremioEditLink}"/>
                <br />
                <h:commandLink action="#{autorPremioController.prepareCreate}" value="#{bundle.ViewAutorPremioCreateLink}" />
                <br />
                <h:commandLink action="#{autorPremioController.prepareList}" value="#{bundle.ViewAutorPremioShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewAutorPremioIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>